stages:
- stage: Windows
  pool:
    vmImage: windows-latest
  jobs:
  - job: win_x64
    variables:
      VSCODE_ARCH: x64
    steps:
      - template: templates/windows.yml

trigger:
  branches:
   include:
   - main
