name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish vscode-windows-ca-certs
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: vscode-windows-ca-certs

        buildSteps:
          - script: npm ci
            displayName: Install dependencies

        testPlatforms:
          - name: Windows
            nodeVersions:
              - 20.x

        testSteps:
          - script: npm ci
            displayName: Install dependencies

          - script: npm run test
            displayName: Compile & test npm package

        apiScanSoftwareName: 'vscode-windows-ca-certs'
        apiScanSoftwareVersion: '0.3'

        publishPackage: ${{ parameters.publishPackage }}
        packagePlatform: Windows
